# Copyright 2025 Lantern Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Governed regeneration of committed projections (CH-0031).

For Lantern maintainers: call write_committed_projections() after any authored
workflow-input change to bring committed projections back into
committed-equals-derived agreement before committing.

SKILL.md and skill-manifest.json are static files (CH-0034) and are not
regenerated by this module.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from lantern.workflow.loader import (
    DEFAULT_BUILTIN_WORKFLOW_MAP_ROOT,
    DEFAULT_CONTRACT_CATALOG_PATH,
    DEFAULT_REGISTRY_PATH,
    DEFAULT_RESOURCE_MANIFEST_PATH,
    DEFAULT_WORKBENCH_BINDINGS_PATH,
    DEFAULT_WORKFLOW_MAP_PATH,
    WorkflowLayer,
    load_workflow_layer,
    render_generated_artifacts,
)


def _canonical_json(payload: Any) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def write_committed_projections(
    *,
    workflow_layer: WorkflowLayer | None = None,
    registry_path: Path | None = None,
    contract_catalog_path: Path | None = None,
    resource_manifest_path: Path | None = None,
    workflow_map_path: Path | None = None,
    workbench_resource_bindings_path: Path | None = None,
    builtin_workflow_map_root: Path | None = None,
) -> None:
    """Write all committed projections from the workflow layer derivation.

    Regenerates resource_manifest.json, contract_catalog.json,
    workbench_registry.yaml, workflow_map.md, workbench_resource_bindings.md,
    and the per-workflow maps under generated/workflow_maps/.

    All path parameters default to the package-default committed-projection
    locations. Accepts overrides so callers (including tests) can redirect output.
    Idempotent: running on an unchanged tree produces a zero diff.

    SKILL.md and skill-manifest.json are static files (CH-0034) and are not
    written by this function.
    """
    layer = workflow_layer if workflow_layer is not None else load_workflow_layer()
    generated = render_generated_artifacts(
        workflow_id=layer.selected_workflow_id,
        workflow_display_name=layer.selected_workflow_display_name,
        runtime_surface_classification=layer.runtime_surface_classification,
        workbenches=layer.workbenches,
        transaction_profiles=layer.transaction_profiles,
        contract_catalog=layer.contract_catalog,
        resource_manifest=layer.resource_manifest,
    )

    reg_path = registry_path if registry_path is not None else DEFAULT_REGISTRY_PATH
    cc_path = contract_catalog_path if contract_catalog_path is not None else DEFAULT_CONTRACT_CATALOG_PATH
    rm_path = resource_manifest_path if resource_manifest_path is not None else DEFAULT_RESOURCE_MANIFEST_PATH
    wm_path = workflow_map_path if workflow_map_path is not None else DEFAULT_WORKFLOW_MAP_PATH
    wb_path = (
        workbench_resource_bindings_path
        if workbench_resource_bindings_path is not None
        else DEFAULT_WORKBENCH_BINDINGS_PATH
    )
    wm_root = builtin_workflow_map_root if builtin_workflow_map_root is not None else DEFAULT_BUILTIN_WORKFLOW_MAP_ROOT

    reg_path.write_text(generated.compatibility_registry_text, encoding="utf-8")
    cc_path.write_text(_canonical_json(generated.contract_catalog_payload), encoding="utf-8")
    rm_path.write_text(_canonical_json(generated.resource_manifest_payload), encoding="utf-8")
    wm_path.write_text(generated.workflow_map_text, encoding="utf-8")
    wb_path.write_text(generated.workbench_resource_bindings_text, encoding="utf-8")
    wm_root.mkdir(parents=True, exist_ok=True)
    (wm_root / f"{layer.selected_workflow_id}.md").write_text(generated.built_in_workflow_map_text, encoding="utf-8")
